
defaults: &defaults
  working_directory: ~/re-resizable
  docker:
    - image: bokuweb/node-go-with-browser:latest
      environment:
        DISPLAY: ":99"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Tsc
          command: yarn run tsc          
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test
            xvfbd stop    
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - add-ssh-keys:
          fingerprints:
            - "45:1a:73:5c:53:97:cc:7d:ef:b0:75:48:93:9f:08:31"          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"          
      - run:
          name: Deploy
          filters:
            branches:
              only: master
          command: yarn run deploy                   
  patch_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "45:1a:73:5c:53:97:cc:7d:ef:b0:75:48:93:9f:08:31"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            sh scripts/deploy-patch.sh
  minor_release:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "45:1a:73:5c:53:97:cc:7d:ef:b0:75:48:93:9f:08:31"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build          
      - run:
          name: Setup git
          command: |
            git config --global user.email "bokuweb12@gmail.com"
            git config --global user.name "bokuweb"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            sh scripts/deploy-minor.sh
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - deploy:
       